; ============================================================================
; Standalone board variants (non-CANopen)
; ============================================================================

[env:seeed_xiao_esp32s3]
extends = env:UC2_3_Xiao
lib_deps =
	milesburton/DallasTemperature@^3.11.0
	paulstoffregen/OneWire@^2.3.7
	adafruit/Adafruit IS31FL3741 Library@^1.2.2
	adafruit/Adafruit BusIO@^1.16.1
	adafruit/Adafruit GFX Library@^1.11.9
	https://github.com/youseetoo/AccelStepper.git
	https://github.com/adafruit/Adafruit_NeoPixel.git
	madhephaestus/ESP32Encoder@^0.12.0
lib_ignore = PSController, M5Dial, M5GFX, M5Unified
build_flags =
	${env:UC2_3_Xiao.build_flags}
	-DCORE_DEBUG_LEVEL=5
	-DESP32S3_MODEL_XIAO=1
	-DMOTOR_CONTROLLER=1	
	-DLASER_CONTROLLER=1
	-DLED_CONTROLLER=1
	-DDIGITAL_IN_CONTROLLER=1
	-DI2C_SLAVE_MOTOR=1
	-DMESSAGE_CONTROLLER=1
	-DUSE_ACCELSTEP=1
	-DLINEAR_ENCODER_CONTROLLER=1
	-DHEAT_CONTROLLER=1
	-DHOME_MOTOR=1
	-DSTAGE_SCAN=1
board_build.cmake_extra_args =
	-DCONFIG=seeed_xiao_esp32s3
	-DCMAKE_C_COMPILER_LAUNCHER=ccache
	-DCMAKE_CXX_COMPILER_LAUNCHER=ccache
	${env:seeed_xiao_esp32s3.build_flags}

[env:seeed_xiao_esp32s3_ledservo]
extends = env:UC2_3_Xiao
platform = https://github.com/platformio/platform-espressif32.git
platform_packages =
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.15
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev//dev/cu.usbmodem1101
board = seeed_xiao_esp32s3
board_build.flash_mode = qio
lib_deps =
	paulstoffregen/OneWire@^2.3.7
  	https://github.com/adafruit/Adafruit_NeoPixel.git
	teemuatlut/TMCStepper@^0.7.3
lib_ignore =
	PSController
build_flags =
	${env:UC2_3_Xiao.build_flags}
	-DCORE_DEBUG_LEVEL=5
	-DESP32S3_MODEL_XIAO=1	
	-DLASER_CONTROLLER=1
	-DLED_CONTROLLER=1
	-DDIGITAL_IN_CONTROLLER=1
	-DMESSAGE_CONTROLLER=1
board_build.cmake_extra_args =
	-DCONFIG=seeed_xiao_esp32s3_ledservo
	${env:seeed_xiao_esp32s3_ledservo.build_flags}

[env:seeed_xiao_esp32s3_ledring]
extends = env:UC2_3_Xiao
platform = https://github.com/platformio/platform-espressif32.git
platform_packages =
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.15
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev//dev/cu.usbmodem1101
board = seeed_xiao_esp32s3
board_build.flash_mode = qio
lib_deps =
	paulstoffregen/OneWire@^2.3.7
  	https://github.com/adafruit/Adafruit_NeoPixel.git
	teemuatlut/TMCStepper@^0.7.3
lib_ignore =
	PSController
build_flags =
	${env:UC2_3_Xiao.build_flags}
	-DCORE_DEBUG_LEVEL=5
	-DESP32S3_MODEL_XIAO=1	
	-DLASER_CONTROLLER=1
	-DDIGITAL_IN_CONTROLLER=1
	-DI2C_SLAVE_LASER=1
	-DMESSAGE_CONTROLLER=1
board_build.cmake_extra_args =
	-DCONFIG=seeed_xiao_esp32s3_ledring
	${env:seeed_xiao_esp32s3_ledring.build_flags}

[env:m5stack_dial]
#platform = espressif32
platform = espressif32 @ 6.9.0
board = m5stack-stamps3
framework =
    arduino
    espidf
upload_speed = 1500000
monitor_filters = esp32_exception_decoder
build_flags =
	-DCORE_DEBUG_LEVEL=5
	-DM5DIAL=1
	-DDIAL_CONTROLLER=1
	-DNODE_ROLE=1
	-DCAN_BUS_ENABLED=1
	-DCAN_CONTROLLER_CANOPEN=1
	-DLASER_CONTROLLER=1
	-DMESSAGE_CONTROLLER=1
	-Wno-format
	-Wunused-variable
	-Wmissing-field-initializers
build_unflags = -Werror=all
lib_deps =
	m5stack/M5Dial
	m5stack/M5GFX
	m5stack/M5Unified
	symlink://lib/uc2_od
	symlink://lib/ESP32_CanOpenNode
lib_ldf_mode = deep+
board_build.cmake_extra_args =
  -DCONFIG=m5stack_dial
  ${env:m5stack_dial.build_flags}
extra_scripts = pre:copy_PinConfig.py

[env:waveshare_esp32s3_ledarray]
extends = env:esp32_framework
upload_port = /dev/cu.usbmodem1101
monitor_port = /dev/cu.usbmodem1101
board = esp32-s3-devkitc-1
board_build.flash_mode = qio
board_build.partitions = custom_partition_esp32s3_waveshare.csv
build_unflags = -std=gnu++11
board_build.f_cpu = 240000000L
board_build.mcu = esp32s3
lib_ignore = PSController
platform = https://github.com/platformio/platform-espressif32.git
platform_packages = 
	framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.17
framework =
	espidf
	arduino
debug_tool = esp-prog
debug_init_break = tbreak setup
lib_deps =
	https://github.com/adafruit/Adafruit_NeoPixel.git
build_flags = 
	-DESP32S3_MODEL_XIAO=1
	-DLED_CONTROLLER=1
	-DMESSAGE_CONTROLLER=1
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
board_build.cmake_extra_args = 
	-DCONFIG=waveshare_esp32s3_ledarray
	-DCMAKE_C_COMPILER_LAUNCHER=ccache
	-DCMAKE_CXX_COMPILER_LAUNCHER=ccache
	${env:waveshare_esp32s3_ledarray.build_flags}
monitor_filters = esp32_exception_decoder
upload_speed = 921600
upload_resetmethod = nodemcu
board_upload.flash_size = 4MB
extra_scripts = pre:copy_PinConfig.py

[env:waveshare_esp32s3_ledarray_debug]
extends = env:waveshare_esp32s3_ledarray
build_flags = 
	${env:waveshare_esp32s3_ledarray.build_flags}
	-DCORE_DEBUG_LEVEL=5

[env:waveshare_esp32s3_7inchScreen]
board = esp32s3box
platform = espressif32@6.9.0
platform_packages = 
	framework-arduinoespressif32 @ 2.0.17
	platformio/framework-espidf   @ ~3.40407.0
framework = 
	espidf
	arduino
monitor_speed = 115200
board_upload.flash_size = 8MB
lib_ignore = PSController
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio
extra_scripts = pre:copy_PinConfig.py
lib_deps = 
	paulstoffregen/OneWire@^2.3.7
	https://github.com/adafruit/Adafruit_NeoPixel.git
	gin66/FastAccelStepper @ ^0.31.5
	teemuatlut/TMCStepper@^0.7.3
	madhephaestus/ESP32Encoder@^0.12.0
build_flags = 
	-DLV_CONF_INCLUDE_SIMPLE=1
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-Wno-format
	-Wunused-variable
	-Wmissing-field-initializers
	-DESP32S3_MODEL_XIAO=1
	-DMESSAGE_CONTROLLER=1
	-DNODE_ROLE=2
	-DCORE_DEBUG_LEVEL=5
	-DMOTOR_CONTROLLER=1
	-DUSE_FASTACCEL=1
	-DCAN_BUS_ENABLED=1
	-DCAN_CONTROLLER_CANOPEN=1
board_build.cmake_extra_args = 
	-DCONFIG=waveshare_esp32s3_7inchScreen
	${env:waveshare_esp32s3_7inchScreen.build_flags}
monitor_filters = esp32_exception_decoder
