; ============================================================================
; UC2 board variants (esp32dev-based)
; ============================================================================

[env:UC2_2_default]
extends = env:esp32dev
lib_deps =
	gin66/FastAccelStepper @ ^0.31.5
	https://github.com/adafruit/Adafruit_NeoPixel.git
	milesburton/DallasTemperature@^3.11.0
	paulstoffregen/OneWire@^2.3.7
	adafruit/Adafruit BusIO@^1.16.1
	adafruit/Adafruit GFX Library@^1.11.9
	robtillaart/TCA9555    @ ^0.4.4
	teemuatlut/TMCStepper@^0.7.3
lib_ignore =
	esp_usb_host_hid
build_flags =
	${env:esp32dev.build_flags}
	-DBLUETOOTH=1
	-DMOTOR_CONTROLLER=1
	#-DWIFI=1
	-DLASER_CONTROLLER=1
	-DLED_CONTROLLER=1
	-DDIGITAL_IN_CONTROLLER=1
	-DHOME_MOTOR=1
	-DMESSAGE_CONTROLLER=1
	-DDAC_CONTROLLER=1
	-DHEAT_CONTROLLER=1
	-DDS18B20_CONTROLLER=1
	-DBTHID=1
	-DUSE_FASTACCEL=1
	-DSTAGE_SCAN=1
board_build.cmake_extra_args =
	-DCONFIG=UC2_2
	${env:UC2_2_default.build_flags}

[env:UC2_2]
extends = env:UC2_2_default
build_flags =
	${env:UC2_2_default.build_flags}
	-DCORE_DEBUG_LEVEL=0

[env:UC2_2_debug]
extends = env:UC2_2_default
build_type = debug
build_flags =
	${env:UC2_2_default.build_flags}
	-DCORE_DEBUG_LEVEL=5

[env:UC2_3_default]
extends = env:esp32dev
lib_deps =
	gin66/FastAccelStepper @ ^0.31.5
	https://github.com/adafruit/Adafruit_NeoPixel.git
	milesburton/DallasTemperature@^3.11.0
	paulstoffregen/OneWire@^2.3.7
	adafruit/Adafruit BusIO@^1.16.1
	adafruit/Adafruit GFX Library@^1.11.9
	robtillaart/TCA9555    @ ^0.4.4
	teemuatlut/TMCStepper@^0.7.3
lib_ignore =
	esp_usb_host_hid
build_flags =
	${env:esp32dev.build_flags}
	-DBLUETOOTH=1
	-DMOTOR_CONTROLLER=1
	#-DWIFI=1
	-DLASER_CONTROLLER=1
	-DLED_CONTROLLER=1
	-DDIGITAL_IN_CONTROLLER=1
	-DUSE_TCA9535=1
	-DHOME_MOTOR=1
	-DMESSAGE_CONTROLLER=1
	-DDAC_CONTROLLER=1
	-DHEAT_CONTROLLER=1
	-DDS18B20_CONTROLLER=1
	-DBTHID=1
	-DUSE_FASTACCEL=1
	-DSTAGE_SCAN=1
board_build.cmake_extra_args =
	-DCONFIG=UC2_3
	${env:UC2_3_default.build_flags}

[env:UC2_3]
extends = env:UC2_3_default
build_flags =
	${env:UC2_3_default.build_flags}
	-DCORE_DEBUG_LEVEL=0

[env:UC2_3_debug]
extends = env:UC2_3_default
build_type = debug
build_flags =
	${env:UC2_3_default.build_flags}
	-DCORE_DEBUG_LEVEL=5

[env:UC2_4_default]
extends = env:esp32dev
lib_deps =
    gin66/FastAccelStepper @ ^0.31.5
	https://github.com/adafruit/Adafruit_NeoPixel.git
	milesburton/DallasTemperature@^3.11.0
	paulstoffregen/OneWire@^2.3.7
	adafruit/Adafruit BusIO@^1.16.1
	adafruit/Adafruit GFX Library@^1.11.9
	robtillaart/TCA9555    @ ^0.4.4
	teemuatlut/TMCStepper@^0.7.3
lib_ignore =
	esp_usb_host_hid
build_flags =
	${env:esp32dev.build_flags}
	-DBLUETOOTH=1
	-DMOTOR_CONTROLLER=1
	#-DWIFI=1
	-DLASER_CONTROLLER=1
	-DLED_CONTROLLER=1
	-DDIGITAL_IN_CONTROLLER=1
	-DUSE_TCA9535=1
	-DHOME_MOTOR=1
	-DMESSAGE_CONTROLLER=1
 	-DHEAT_CONTROLLER=1
	-DDS18B20_CONTROLLER=1
	-DBTHID=1
	-DUSE_FASTACCEL=1
	-DSTAGE_SCAN=1
board_build.cmake_extra_args =
	-DCONFIG=UC2_4
	-DCMAKE_C_COMPILER_LAUNCHER=ccache
	-DCMAKE_CXX_COMPILER_LAUNCHER=ccache
	${env:UC2_4_default.build_flags}

[env:UC2_4]
extends = env:UC2_4_default
build_flags =
	${env:UC2_4_default.build_flags}
	-DCORE_DEBUG_LEVEL=0

[env:UC2_4_debug]
extends = env:UC2_4_default
build_type = debug
build_flags =
	${env:UC2_4_default.build_flags}
	-DCORE_DEBUG_LEVEL=5

[env:UC2_WEMOS]
extends = env:UC2_3_default
build_flags =
	${env:UC2_3_default.build_flags}
	-DCORE_DEBUG_LEVEL=0

[env:UC2_WEMOS_debug]
extends = env:UC2_3_default
build_type = debug
build_flags =
	${env:UC2_3_default.build_flags}
	-DCORE_DEBUG_LEVEL=5
