[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
    -DCAN_TX_PIN=17
    -DCAN_RX_PIN=18
    -DCAN_BITRATE_KBPS=500
    ; LISTEN_ONLY=1 -> no ACKs, completely passive (safe sniff)
    ; LISTEN_ONLY=0 -> NORMAL mode, generates ACKs (acts as a real node)
    -DLISTEN_ONLY=1
