# PlatformIO pre-script: bake the firmware release identity into the build.
#
# Writes main/uc2_fw_version.h (gitignored, like main/PinConfig.h) with
# UC2_FW_VERSION. The firmware reports it as "identifier_version" in /state_get
# and in CANopen OD 0x2500 (the bus scan's "fwVersion"); the frame build also
# publishes it in version.json on the firmware server, so ImSwitch can compare
# what a board runs with what the server offers.
#
# CI sets UC2_FW_VERSION (.github/workflows/build-frame.yaml). Local builds
# derive the same format from git: the exact v* tag when HEAD is tagged,
# otherwise `git describe` + "-t<author time, UTC>", plus "-dirty" when tracked
# files have uncommitted changes.
#
# The header is only rewritten when the string changes, so only the two files
# that include it recompile.
import json
import os
import subprocess
from datetime import datetime, timezone

Import("env")

PROJECT_DIR = env.subst("$PROJECT_DIR")


def _git(*args):
    return subprocess.check_output(
        ["git", *args], cwd=PROJECT_DIR, text=True, stderr=subprocess.DEVNULL
    ).strip()


def git_version():
    try:
        tag = _git("describe", "--tags", "--exact-match", "--match", "v*", "HEAD")
    except subprocess.CalledProcessError:
        tag = ""
    try:
        version = _git("describe", "--tags", "--match", "v*", "--abbrev=7", "--always", "HEAD")
        if version != tag:
            ts = int(_git("show", "-s", "--format=%at", "HEAD"))  # author time, like CI's %ad
            version += datetime.fromtimestamp(ts, timezone.utc).strftime("-t%Y%m%d%H%M%S")
        if subprocess.call(["git", "diff", "--quiet", "HEAD"], cwd=PROJECT_DIR) != 0:
            version += "-dirty"
        return version
    except (OSError, subprocess.CalledProcessError, ValueError):
        return "unknown"


version = os.environ.get("UC2_FW_VERSION", "").strip() or git_version()
print(f"UC2 firmware version: {version}")

header = os.path.join(PROJECT_DIR, "main", "uc2_fw_version.h")
content = (
    "// Generated by tools/fw_version.py - do not edit, do not commit.\n"
    "#pragma once\n"
    f"#define UC2_FW_VERSION {json.dumps(version)}\n"
)
try:
    with open(header) as f:
        unchanged = f.read() == content
except OSError:
    unchanged = False
if not unchanged:
    with open(header, "w") as f:
        f.write(content)
