# PlatformIO pre-script: bake the firmware release identity into the build.
#
# Writes main/uc2_fw_version.h (gitignored, like main/PinConfig.h) with
# UC2_FW_VERSION. The firmware reports it as "identifier_version" in /state_get
# and in CANopen OD 0x2500 (the bus scan's "fwVersion"); the frame build also
# publishes it in version.json on the firmware server, so ImSwitch can compare
# what a board runs with what the server offers.
#
# Also UC2_FW_IMAGE: the image file this build becomes on the firmware server
# (esp32_<env>[_mot<axis>].bin), reported as "identifier_image" / OD 0x2501
# ("fwImage"), so ImSwitch updates each board with the image it was built as.
# CI passes the exact name; locally it is derived from the env and CAN_AXIS_ID.
#
# CI sets UC2_FW_VERSION (.github/workflows/build-frame.yaml). Local builds
# derive the same format from git: the exact v* tag when HEAD is tagged,
# otherwise `git describe` + "-t<author time, UTC>", plus "-dirty" when tracked
# files have uncommitted changes.
#
# The header is only rewritten when a string changes, so only the two files
# that include it recompile.
import json
import os
import re
import subprocess
from datetime import datetime, timezone

Import("env")

PROJECT_DIR = env.subst("$PROJECT_DIR")


def _git(*args):
    return subprocess.check_output(
        ["git", *args], cwd=PROJECT_DIR, text=True, stderr=subprocess.DEVNULL
    ).strip()


def git_version():
    try:
        tag = _git("describe", "--tags", "--exact-match", "--match", "v*", "HEAD")
    except subprocess.CalledProcessError:
        tag = ""
    try:
        version = _git("describe", "--tags", "--match", "v*", "--abbrev=7", "--always", "HEAD")
        if version != tag:
            ts = int(_git("show", "-s", "--format=%at", "HEAD"))  # author time, like CI's %ad
            version += datetime.fromtimestamp(ts, timezone.utc).strftime("-t%Y%m%d%H%M%S")
        if subprocess.call(["git", "diff", "--quiet", "HEAD"], cwd=PROJECT_DIR) != 0:
            version += "-dirty"
        return version
    except (OSError, subprocess.CalledProcessError, ValueError):
        return "unknown"


def image_name():
    # Same naming as build-frame.yaml: CAN motor slaves are built once per axis
    # via -DCAN_AXIS_ID=CAN_ID_MOT_<X> and published as ..._mot<X>.bin
    flags = " ".join(map(str, env.get("BUILD_FLAGS", []))) + " " + os.environ.get(
        "PLATFORMIO_BUILD_FLAGS", "")
    axis = re.search(r"CAN_AXIS_ID=CAN_ID_MOT_([XYZA])\b", flags)
    return f"esp32_{env.subst('$PIOENV')}{'_mot' + axis.group(1) if axis else ''}.bin"


version = os.environ.get("UC2_FW_VERSION", "").strip() or git_version()
image = os.environ.get("UC2_FW_IMAGE", "").strip() or image_name()
print(f"UC2 firmware version: {version} ({image})")

header = os.path.join(PROJECT_DIR, "main", "uc2_fw_version.h")
content = (
    "// Generated by tools/fw_version.py - do not edit, do not commit.\n"
    "#pragma once\n"
    f"#define UC2_FW_VERSION {json.dumps(version)}\n"
    f"#define UC2_FW_IMAGE {json.dumps(image)}\n"
)
try:
    with open(header) as f:
        unchanged = f.read() == content
except OSError:
    unchanged = False
if not unchanged:
    with open(header, "w") as f:
        f.write(content)
